#!/bin/bash

install_program() {
  which $1 &>/dev/null
  if [ "$?" != "0" ]; then
    printf "installing $1... "
    apt-get install -y $1 &>/dev/null
    if [ "$?" == "0" ]; then
      echo "done"
    else
      yum install -y $1 &>/dev/null
      if [ "$?" == "0" ]; then
        echo "done"
      else
        echo "failed"
      fi
    fi
  else
    return 1
  fi
}

remove_program() {
  printf "removing $1... "
  apt-get purge -y $1 &>/dev/null
  if [ "$?" == "0" ]; then
    echo "done"
  else
    yum remove -y $1 &>/dev/null
    if [ "$?" == "0" ]; then
      echo "done"
    else
      echo "failed"
    fi
  fi
}

create_script() {
  printf "creating the $2 script... "
  printf "$1" >$2
  chmod 755 $2
  chown root:root $2
  if [ "$?" == "0" ]; then
    echo "done"
  else
    echo "failed"
  fi
}

create_systemd_service() {
  printf "$1" >/etc/systemd/system/$2
  systemctl daemon-reload
  printf "enabling $2... "
  systemctl enable $2 &>/dev/null
  if [ "$?" == "0" ]; then
    echo "done"
  else
    echo "failed"
  fi
  printf "starting $2... "
  systemctl stop $2 &>/dev/null
  systemctl start $2 &>/dev/null
  if [ "$?" == "0" ]; then
    echo "done"
  else
    echo "failed"
  fi
}

finish() {
  if [ "$?" == "0" ]; then
    echo "done"
  else
    echo "failed"
  fi
}

#--------------------------------------------------------------------------------
create_rc_service() {
  for i in {1..5}; do
    ln -s -f $1 /etc/rc$i.d/S90$2
    chown -h root:root /etc/rc$i.d/S90$2
  done
}
