#!/bin/bash

install_program() {
  which dpkg &>/dev/null
  if [ "$?" == "0" ]; then
    dpkg -s $1 &>/dev/null
    if [ "$?" != "0" ]; then
      printf "installing $1... "
      apt-get install -y $1 &>/dev/null
      if [ "$?" == "0" ]; then
        echo "done"
        return 0
      else
        echo "failed"
        return 1
      fi
    fi
    return 1
  fi
  which yum &>/dev/null
  if [ "$?" == "0" ]; then
    yum list installed $1 &>/dev/null
    if [ "$?" != "0" ]; then
      printf "installing $1... "
      yum install -y $1 &>/dev/null
      if [ "$?" == "0" ]; then
        echo "done"
        return 0
      else
        echo "failed"
        return 1
      fi
    fi
    return 1
  fi
  return 1
}

remove_program() {
  printf "removing $1... "
  which dpkg &>/dev/null
  if [ "$?" == "0" ]; then
    apt-get purge -y $1 &>/dev/null
    finish
  else
    which yum &>/dev/null
    if [ "$?" == "0" ]; then
      yum remove -y $1 &>/dev/null
      finish
    fi
  fi
}

create_script() {
  printf "creating the $2 script... "
  printf "$1" >$2
  chmod 755 $2
  chown root:root $2
  if [ "$?" == "0" ]; then
    echo "done"
  else
    echo "failed"
  fi
}

create_systemd_service() {
  printf "$1" >/etc/systemd/system/$2
  systemctl daemon-reload
  printf "enabling $2... "
  systemctl enable $2 &>/dev/null
  if [ "$?" == "0" ]; then
    echo "done"
  else
    echo "failed"
  fi
  printf "starting $2... "
  systemctl stop $2 &>/dev/null
  systemctl start $2 &>/dev/null
  if [ "$?" == "0" ]; then
    echo "done"
  else
    echo "failed"
  fi
}

finish() {
  if [ "$?" == "0" ]; then
    echo "done"
    return 0
  else
    echo "failed"
    return 1
  fi
}

#--------------------------------------------------------------------------------
create_rc_service() {
  for i in {1..5}; do
    ln -s -f $1 /etc/rc$i.d/S90$2
    chown -h root:root /etc/rc$i.d/S90$2
  done
}
